- Gemfile
- Gemfile.lock
- app/views/adopters/show.html.erb
- app/views/dogs/index.html.erb
- app/views/dogs/show.html.erb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/staging.rb
Get that CACHE playa
:moneybag: :moneybag:  :moneybag:  :moneybag:
> Memcache prep

- Gemfile
- Gemfile.lock
- app/controllers/dogs_controller.rb
- app/helpers/application_helper.rb
- app/models/dog_searcher.rb
- spec/controllers/dogs_controller_spec.rb
- spec/models/dog_searcher_spec.rb
- spec/spec_helper.rb
* Adds json_spec for rspec json helpers
* Configures JSON helpers
* Adds tests for index method, all if / else paths
First Commit, add tests: https://github.com/ophrescue/RescueRails/commit/d17773dcd469241f898b927f7d5fed0d75520203
> DogsController#index tests

- app/models/dog_searcher.rb
- spec/models/dog_searcher_spec.rb
Also adds test for name case.
The weird part about this is the tests pass fine. I think there's something strange going on with the will_paginate or something in the view, maybe it won't query the photos and breed until you go to display it?  I also find it strange that only 2 fields are being selected out in the sql that bombs.
> Fix for ambiguous name field

- Gemfile
- Gemfile.lock
> Updates Rollbar Gem

- app/controllers/adopters_controller.rb
- app/models/adopter_searcher.rb
- spec/models/adopter_searcher_spec.rb
Adopter controller gets the dog controller treatment.
* Move index search code to AdopterSearcher
* AdopterSearcher spec
* Create load_adopter before_filter
> Adopter controller clean up

- spec/models/adopter_searcher_spec.rb
How was this working at all?  Wrong model stupid head!
> Copy / Paste woops

- app/models/user.rb
- spec/factories/user.rb
- spec/models/user_spec.rb
Fairly simple stuff, check it out @TheDudeWithTheThing
> adds validation and tests for user state and zip code

- app/controllers/pages_controller.rb
> resolves #385 unneeded call to events on home page

- app/controllers/users_controller.rb
- app/models/concerns/filterable.rb
- app/models/user.rb
- app/views/users/_foster_filters.html.erb
- app/views/users/_user_table.html.erb
- app/views/users/index.html.erb
- config/application.rb
- config/initializers/rollbar.rb
* Filterable concern
* Many new scopes for user
* active no longer in all scopes
* Disable rollbar in non production environments
> Foster filtering resolves #314

- Gemfile
- Gemfile.lock
- app/assets/javascripts/photos.js.coffee
- app/assets/stylesheets/custom.css.scss
- app/controllers/photos_controller.rb
- app/models/dog.rb
- app/models/photo.rb
- app/views/dogs/edit.html.erb
Resolves #392 
I think the problem was that the sort wasn't respecting the scope in all instances.  So there were some points where the entire Photos table was getting sorted.
Whoops :hankey:
> 392 image sort bug

- app/assets/javascripts/adoption_form.js
- app/views/adopters/_adopter_form.html.erb
#394 Phone number for adopters now editable inline.
> 394 edit adopter phone number

- app/models/dog.rb
- app/views/dogs/edit.html.erb
- app/views/dogs/show.html.erb
- db/migrate/20150912175211_add_medical_notes_to_dog.rb
- db/schema.rb
Has a migration so be sure to run `rake db:migrate`
Adds form field for medical notes to dog edit screen.
> Adds medical notes to dog

- .travis.yml
- Gemfile
- Gemfile.lock
- app/controllers/users_controller.rb
- app/models/user.rb
- script/topological_sort.rb
- spec/controllers/users_controller_spec.rb
- spec/factories/user.rb
- spec/features/apply_to_adopt_spec.rb
Work Completed on User Model & Ready to Merge :  In support of #409 
My first attempt at setting up strong parameters for the User model/controller.  
Please check this out and make sure I'm moving in the right direction before I attack the rest of the application.  
Will need to remove the commented out code still too.
> Strong Paramaters for User Model

- app/controllers/comments_controller.rb
- app/models/adopter.rb
- app/models/adoption.rb
- app/models/adoption_app.rb
- app/models/attachment.rb
- app/models/banned_adopter.rb
- app/models/breed.rb
- app/models/comment.rb
- app/models/dog.rb
- app/models/event.rb
- app/models/folder.rb
- app/models/photo.rb
- app/models/reference.rb
- app/models/shelter.rb
- app/models/user.rb
- config/initializers/strong_parameters.rb
> Strong params are done!

- app/controllers/users_controller.rb
- app/views/users/index.html.erb
- spec/controllers/users_controller_spec.rb
Okay all done!  I'm sure this could use some polish in terms of UI stuff, but we can tackle that as part of the bootstrap upgrade.
> implement volunteer search for #391

- app/views/adopters/_adopter_form.html.erb
- spec/factories/adopter.rb
- spec/factories/adoption_app.rb
- spec/features/view_adoption_app_spec.rb
@TheDudeWithTheThing is there a better control structure to do for this?  Or is this a good choice?
> fix for nil max hrs alone

- app/helpers/adopters_helper.rb
- app/views/adopters/_adopter_form.html.erb
@TheDudeWithTheThing thanks for the advice, how's this look?
> refactor max hrs alone to use a view helper

- app/controllers/attachments_controller.rb
- app/controllers/users_controller.rb
- app/helpers/users_helper.rb
- app/models/attachment.rb
- app/models/user.rb
- app/views/users/_form.html.erb
- app/views/users/show.html.erb
- db/migrate/20160326193338_add_confidentiality_agreement_to_users.rb
- db/migrate/20160412003809_add_agreement_type_to_attachments.rb
- db/migrate/20160412010043_set_agreement_types_for_attachable.rb
- db/schema.rb
- spec/controllers/users_controller_spec.rb
- spec/features/attach_agreement_to_user.rb
- spec/features/attach_agreement_to_user_spec.rb
- spec/models/user_spec.rb
Okay, I can't figure out what I'm doing wrong here...
> DONE - Add Confidentiality Agreement

- app/jobs/adopter_subscribe_job.rb
- app/jobs/adopter_unsubscribe_job.rb
- app/jobs/user_subscribe_job.rb
- app/jobs/user_unsubscribe_job.rb
- app/models/adopter.rb
- app/models/user.rb
- app/services/mail_chimp_service.rb
- config/application.rb
So, this doesn't seem to work.  I'm getting the following error in delayed_job
````
undefined local variable or method `new' for #<UserSubscribeJob:0x007fd1bb4ec4f8>
/Users/mark/rails_projects/RescueRails/app/jobs/user_subscribe_job.rb:8:in `perform'
/Users/mark/.rvm/gems/ruby-2.2.3/gems/activejob-4.2.6/lib/active_job/execution.rb:32:in `block in perform_now'
/Users/mark/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:117:in `call'
````
I'm not sure where the ```new``` method you use in ```MailChimpService``` is actually coming from
I'm also guessing there is a much cleaner way to handle this, but one step at a time.
> WIP #434 ActiveJob Mailchimp attempt

- app/models/mail_chimp_client.rb
- config/mailchimp.yml
- db/seeds.rb
Left interest ids even though they're not used, I also need the right interest ids for test, which I'll modify in the other PR.
> Moves mailchimp vars to env

- Gemfile
- Gemfile.lock
- app/models/attachment.rb
- app/models/photo.rb
- app/views/dogs/show.html.erb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/staging.rb
- config/initializers/papertrail.rb
> Upgrade gem aws sdk

- app/assets/javascripts/application.js
- app/assets/javascripts/dog_token.js
- app/controllers/dogs_controller.rb
- app/views/adopters/steps/_dog.html.erb
- config/routes.rb
- spec/controllers/dogs_controller_spec.rb
I noticed this dead stuff while trying to do the endless scroll.  Having the JSON format in the dogs#index was blocking me from doing the endless scroll the easy way.  If we don't need that dog token stuff (which was commented out) then let's lose it.
Some rubocop clean up too.
> Removes dead code

- app/controllers/adopters_controller.rb
- app/controllers/adoption_app_controller.rb
- app/models/adoption_app.rb
- app/views/adopters/_adopter_form.html.erb
- app/views/adopters/show.html.erb
> Adds ability to upload documents to adoption application

- app/controllers/application_controller.rb
- app/controllers/dogs_controller.rb
- app/models/dog.rb
- app/views/dogs/show.html.erb
- spec/controllers/dogs_controller_spec.rb
Call me Mayor Goldie Wilson cause I'm cleaning up this town
> Dog controller tests

- app/views/dogs/_manager.html.erb
- app/views/dogs/_manager_dog.html.erb
This is ready to go.  Short and sweet.
> adds intake_dt to dog mgr index

- app/assets/javascripts/rescue_rails.js
- app/controllers/dogs_controller.rb
- app/models/dog_searcher.rb
- app/views/dogs/_dog.html.erb
- app/views/dogs/_manager.html.erb
- app/views/dogs/index.html.erb
- app/views/dogs/index.js.erb
Both gallery and manager views.
Not as much test coverage as I like but you can at least play with it and see how she rides.
> Adds endless scrolling to dog search

- app/views/users/_user_table.html.erb
- app/views/users/index.html.erb
- app/views/users/index.js.erb
Looked at how to implemented this for the dog view and went ahead and added the extra javascript for it to work for users too!
> fixes #469 by making infinite scroll work for users views

- app/assets/stylesheets/custom.scss
- app/views/dogs/_dog_rows.html.erb
- app/views/dogs/index.html.erb
- app/views/dogs/index.js.erb
> Adds a height to the li element of gallery

- app/views/dogs/_manager.html.erb
- app/views/dogs/index.html.erb
@markottaviani k manager and regular view look good now, sorry bout that.
> Fixes manager view for infinite scroll

- .rubocop.yml
- app/models/adopter_searcher.rb
- app/views/adopters/index.html.erb
- app/views/adopters/index.js.erb
For https://github.com/ophrescue/RescueRails/issues/470
> Adds infinite scroll to adopters index

- app/views/adopters/_adopter.html.erb
- app/views/adopters/index.html.erb
Quick enable of sortable for adoption columns that don't depend on a join.
> Adopter sorts ez

- app/models/adopter_searcher.rb
- app/views/adopters/index.html.erb
This is an attempt at #497 However it doesn't work right, and I'm not sure exactly how to handle this sort, as I want sort adopters by the timestamp of the most recent comment on their application.
> Sort Adopters by Last Comment on each App?

- app/assets/javascripts/application.js
- vendor/assets/javascripts/jquery_ujs.js
From bug reported.  Ajax requests were missing the X-CSRF-Token header from removing jquery-ujs
> Adds jquery_ujs to fix CSRF bug

- Gemfile
- Gemfile.lock
Updating gems that will be used in Rails 5
> General gem updates

- app/controllers/adopters_controller.rb
- app/controllers/adoption_app_controller.rb
- app/models/adoption_app.rb
- app/views/adopters/_adopter_other_pets.html.erb
- app/views/adopters/steps/_other_pets.html.erb
- db/migrate/20160904204259_add_shots_to_app.rb
- db/schema.rb
- spec/features/apply_to_adopt_spec.rb
- spec/models/adoption_app_spec.rb
Pretty routine set of changes.  Adds new medication questions as requested for #488
> adds new meds questions to adopt app

- app/assets/javascripts/dog_link.js
- app/views/adopters/_associated_dogs_form.html.erb
Fairly straight forward, not sure if specifying an ID for the button is "best practice" or I should get at the buttom via DOM traversal a different way.
> fix for link dog button getting stuck as disabled

- app/assets/javascripts/adoption_app_wizard.js
- app/views/adopters/new.html.erb
- app/views/adopters/steps/_reference_fields.html.erb
- vendor/assets/javascripts/jquery.validate.js
Attempt at #531 , some weird behavior where clicking on and off the relationship box causes it to go true, but it at least gets the point across to folks applying.
> closed #531 reference relationship checker

- app/models/dog.rb
- app/models/user.rb
- db/migrate/20170108171855_add_pr_fund_to_users.rb
- db/schema.rb
- spec/models/dog_spec.rb
- spec/models/user_spec.rb
Puts new columns in place for #533
> Database changes for #533 New User Categories

- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/users/_form.html.erb
- app/views/users/_permissions.html.erb
- app/views/users/index.html.erb
- spec/controllers/users_controller_spec.rb
Fairly Straight Forward Code Changes, completes #533
> closes #533 New PR and Funding User Categories

- app/assets/javascripts/adoption_app_home_auth.js
- app/assets/javascripts/adoption_app_wizard.js
- app/assets/javascripts/application.js
- app/controllers/adopters_controller.rb
- app/controllers/adoption_app_controller.rb
- app/models/adoption_app.rb
- app/views/adopters/_adopter_form.html.erb
- app/views/adopters/steps/_your_home.html.erb
- db/migrate/20170110012637_add_verify_home_auth_to_adoption_app.rb
- db/schema.rb
- spec/features/apply_to_adopt_spec.rb
- spec/models/adoption_app_spec.rb
includes show/hide of field if home type of own is set
and display of authorization if required approval was captured.
> closes #540 home verification auth to adopt app

- spec/features/apply_to_adopt_spec.rb
- spec/features/edit_adopter_spec.rb
never make that mistake again!   Tests!
Also I think the newer version of capybara makes it so we can remove the sleeps
> Adds test for massive flub with adopter edit

- app/controllers/events_controller.rb
- spec/features/apply_to_adopt_spec.rb
* 	needed to add one sleep back for local testing, otherwise got weird stuff like this in the Landlord Phone Number:
* Also fixed 500 error when going to events/:id/:edit and not already being logged in.
> Test Tidy Up and Minor Bug Fix

- app/controllers/dogs_controller.rb
- app/models/adopter.rb
- app/models/concerns/auditable.rb
- app/models/dog.rb
Extracts audit code to an Auditable concern, which made auditing dog status a snap.
Closes #562
> Track dog status

- app/views/layouts/_stylesheets.html.erb
- app/views/layouts/_topbar.html.erb
Just a quick tweak, but when printing a dog's public profile it at least looks a lot better.
> improve how dogs look when printing

- db/migrate/20170418220414_add_county_to_adopters.rb
- db/schema.rb
Deploy and run this before pushing the geocode-county branch
> Adds migration to add county to Adopter

- app/models/adopter.rb
- app/services/county_service.rb
- app/views/adopters/_adopter_form.html.erb
- db/migrate/20170418220414_add_county_to_adopters.rb
- db/schema.rb
- spec/models/adopter_spec.rb
- spec/services/county_service_spec.rb
> Populates adopter.county when zip changes

- app/models/dog_searcher.rb
> eagar load dog index

- app/views/dogs/index.html.erb
Nice and simple and seems to work well locally.  Pushing this out and will monitor logs/performance for anything weird.
> enable caching for public dog index #586

- app/models/adopter.rb
- app/views/adopters/steps/_preq.html.erb
- spec/features/apply_to_adopt_spec.rb
Text updates to the pre-application adoption agreement.
> update to adopt app terms and conditions

- Gemfile.lock
- app/controllers/users_controller.rb
- app/views/users/_form.html.erb
- app/views/users/edit.html.erb
- spec/features/edit_user_profile_spec.rb
PR for issue #584 
* updated `_form.html.erb` to display disabled name/email fields to non-admin users
* updated `user_params` accordingly
* created feature tests
> Field restrictions #584

- app/helpers/application_helper.rb
PR for issue #592 
*added `search_term` to the `link_to` UrlHelper inside the `sortable` method
> added search_term variable  to sortable method

- app/models/photo.rb
- app/views/dogs/_dog_rows.html.erb
Caches at the dog level, not sure how much this will buy us in terms of performance gains but should be ok.  My environment is a little messed up so I can't try this out until I fix that.
> Caches dogs at the row level

- app/controllers/users_controller.rb
- app/models/user_searcher.rb
- app/views/users/_user.html.erb
- app/views/users/_user_table.html.erb
- app/views/users/index.html.erb
- spec/controllers/users_controller_spec.rb
- spec/models/user_searcher_spec.rb
PR for ticket #583 
* name and email can be searched from the same input field
* created controller test
One thing to note: When searching by email a full email address has to be submitted. It does not work with a 'partial' address. Did we want to have that work? 
I was trying to figure out how to 'clean' up the `params` if statement inside the `index` method. Would love to hear suggestions on how to make it a bit tidier if anything comes to mind.
> #583_User_Email_Search

- app/models/adopter_searcher.rb
- spec/models/adopter_searcher_spec.rb
PR for #599
* added `email_search?` method to `adopter_searcher`
* added test
> WIP #599_added_email_search_for_adopters

- app/models/dog_searcher.rb
- spec/models/dog_searcher_spec.rb
PR for #570 
* dogs that have a name with a number at the beginning can now be searched
> 4 seasons now works

- app/controllers/users_controller.rb
- app/models/user.rb
- app/models/user_searcher.rb
- app/views/users/_form.html.erb
- app/views/users/_user.html.erb
- app/views/users/_user_table.html.erb
- app/views/users/index.html.erb
- app/views/users/show.html.erb
- db/migrate/20170813121555_add_translator_fields_to_users.rb
- db/schema.rb
- spec/controllers/users_controller_spec.rb
PR for #608 
* User can now specify if they can translate English into one or more languages and they can list out those languages
* User #show page will indicate when a user has listed translation languages
* User #index page now has a translator filter tab
> Translator #608

- app/views/folders/_folder.html.erb
- app/views/folders/_folder_table.html.erb
- app/views/folders/index.html.erb
> Improve Staff Folder UI

- app/views/users/_user.html.erb
- app/views/users/_user_table.html.erb
Removed some unneeded columns that eat up space. Pending feedback https://www.facebook.com/groups/348416295253712/permalink/1407803099315021/
> cleaned up user index

- app/controllers/users_controller.rb
- app/models/attachment.rb
- app/models/user.rb
- app/views/users/_form.html.erb
- app/views/users/show.html.erb
- db/migrate/20170912022717_add_code_of_conduct_agreement_to_users.rb
- db/schema.rb
- spec/features/attach_agreement_to_user_spec.rb
Closes #620 adding a code of conduct file attachment to the user profile.
> #620 code of conduct for user profile

- db/migrate/20170917020834_add_behavior_summary_to_dog.rb
- db/schema.rb
> db changes for #614 behavior summary

- .rubocop_todo.yml
- app/controllers/dogs_controller.rb
- app/models/adoption_app.rb
- app/models/dog.rb
- app/models/user.rb
- app/views/dogs/edit.html.erb
- app/views/dogs/show.html.erb
- spec/controllers/dogs_controller_spec.rb
- spec/models/adoption_app_spec.rb
- spec/models/dog_spec.rb
- spec/models/user_spec.rb
Database changes already applied.
> 614 dog behavior summary

- app/models/event.rb
Some extra Event Validation to cut down on errors caused by people pasting in HUGE URLS.
> Event validation

- app/models/adopter.rb
- app/models/adoption_app.rb
- spec/factories/adoption_app.rb
Adding some additional server side validations since we've been getting some weird spam garbage submissions hitting the error logs.
> More adopter validations

- .rubocop.yml
- .rubocop_todo.yml
- app/controllers/adoptions_controller.rb
- app/controllers/banned_adopters_controller.rb
- app/models/mail_chimp_client.rb
These were annoying me while working on something else.
Enjoy!
> Fixes Layout/MultilineMethodCallIndentation and Layout/EndAlignment

- app/models/dog_searcher.rb
- spec/models/dog_searcher_spec.rb
This switches us back to the old sorting methods, and as the fix still didn't sort correctly and also broke the by column sorting.  I moved the code around a little bit so it's easier to see what's going on.  I also added new tests to very at the column by column sorting works.
> Added ranking and sorting tests and fix regression

- app/models/dog_searcher.rb
- spec/models/dog_searcher_spec.rb
What a n00b
What did we learn here?
* to pass in bind params to order by you pass in an array
* bind params will be quoted properly, so don’t do that for normal sorts
* assign results back to the var, don't be a n00b
> Fixes the ranking for real

- Gemfile
- Gemfile.lock
- config/environments/development.rb
- config/environments/production.rb
- config/environments/staging.rb
- lib/tasks/adoptapet_sync.rake
closes #658 and includes exception monitoring for rake tasks
> Fixes adoptapet sync

- Gemfile
- Gemfile.lock
- spec/controllers/comments_controller_spec.rb
- spec/factories/adopter.rb
- spec/factories/adoption.rb
- spec/factories/adoption_app.rb
- spec/factories/attachment.rb
- spec/factories/bannded_adopter.rb
- spec/factories/breed.rb
- spec/factories/comment.rb
- spec/factories/dog.rb
- spec/factories/event.rb
- spec/factories/folder.rb
- spec/factories/photo.rb
- spec/factories/reference.rb
- spec/factories/shelter.rb
- spec/factories/user.rb
- spec/rails_helper.rb
FactoryGirl was renamed to FactoryBot, see https://robots.thoughtbot.com/factory_bot
> Update FactoryGirl to FactoryBot

- app/assets/javascripts/application.js
- app/assets/javascripts/photos.js
- vendor/assets/javascripts/jquery.ui.touch-punch.min.js
Connects to #679
Allows dog photos to be sorted while using touch devices!
> dog photos sortable on touch devices

- app/views/pages/foster.html.erb
- app/views/pages/fosterfaq.html.erb
- app/views/pages/volunteer.html.erb
> change emailmeform to https

- app/models/attachment.rb
- app/models/folder.rb
- config/environments/development.rb
> Modifies development to use file storage instead of S3

- app/controllers/dogs_controller.rb
- app/controllers/sessions_controller.rb
- app/views/dogs/index.html.erb
> 671 dogs index render bug

- app/views/pages/contributors.html.erb
- app/views/pages/partnerships.html.erb
> move event and boarding hosts to partnership page

- config/routes.rb
Redirect to 5k Registration website at `/5k` .
> add redirect for upcoming 5k

- app/mailers/training_mailer.rb
- app/views/pages/training_partners.html.erb
minor page changes for the oph dog training program
> Training page add mindy contact info

- Gemfile
- Gemfile.lock
I'm assuming the defaults are ok for us for now.  If we notice and strangeness we can tweak.
> Removes unicorn in favor of puma

- Gemfile
Reverts ophrescue/RescueRails#752
This is going to require a bunch of server reconfigurations, still want to do it but is going to require a bunch of work in staging to accommodate properly.
> Revert "Removes unicorn in favor of puma"

- app/models/dog.rb
- spec/controllers/dogs_controller_spec.rb
Historically the dog gallery has always been sorted by dog tracking_id.  Adds back in and includes a test
> returned undocumented feature of sort by tracking_id

- app/controllers/dogs_controller.rb
- app/helpers/dogs_helper.rb
- app/models/dog_filter.rb
- app/models/dog_search.rb
- app/views/dogs/_manager.html.erb
- app/views/dogs/index.html.erb
- app/views/dogs/manager_index.html.erb
- config/routes.rb
- spec/controllers/dogs_controller_spec.rb
- spec/features/dog_filter_spec.rb
- spec/features/dog_search_spec.rb
- spec/helpers/application_helpers.rb
- spec/models/dog_filter_spec.rb
- spec/models/dog_search_spec.rb
- spec/models/dog_spec.rb
cleans up the horribly overloaded DogsController#index method by splitting off the authenticated cases into their own #manager_index method, including its own manager_index view. This turns out to simplify many things.
> Issue771 fix

- app/views/pages/resources.html.erb
This adds a requested article to the adoption resources page, as well as opens external links in new tabs.
> open external links in new tabs and add resource article

- app/models/concerns/sortable.rb
- spec/helpers/dogs_list_helper.rb
- spec/helpers/rspec_matchers.rb
- spec/models/dog_search_spec.rb
no production code changed, just rspec matcher and an rspec test added to confirm that the matcher is working as expected
> fix occasional test error due to custom rspec matcher bug

- app/controllers/adopters_controller.rb
- app/controllers/dogs_controller.rb
- app/models/dog.rb
- app/views/adopters/_adopt_success_message.erb
- app/views/dogs/_unavailable_flash_message.erb
- app/views/dogs/show.html.erb
- app/views/layouts/application.html.erb
- spec/features/dog_show_spec.rb
- spec/helpers/dogs_list_helper.rb
- spec/helpers/rspec_matchers.rb
- spec/models/dog_search_spec.rb
because I get a little agita when I see flash messages hard-coded in the view. There are others but this is a couple of a quick spot fixes. The (late) great rubyist Jim Weirich taught me.... "always leave the code cleaner than you found it"
> Flash refactor

- .gitignore
- app/controllers/dogs_controller.rb
- spec/features/dog_access_spec.rb
when user is logged-in and not active, they are shown the 'standard' DogsController#index page with heading "Our Dogs'. It's not a redirect, there's no flash message, they just see something different from what an active user sees.
> test for, and fix access to manager view

- app/assets/stylesheets/custom.scss
- app/views/pages/international-article.html.erb
- app/views/pages/international-kaw.html.erb
- app/views/pages/international-tcspca.html.erb
- app/views/pages/international.html.erb
- config/routes.rb
New section on OPH International Programs, photos to be added later. These pages are not referenced anywhere on the site yet so they'll be a "dark deploy" so that the Rescue can do a review and provide feedback.
> International Program Pages Initial Draft

- app/assets/stylesheets/custom.scss
- app/views/pages/international-kaw.html.erb
- app/views/pages/international-tcspca.html.erb
- app/views/pages/international.html.erb
Revisions for the Draft International Pages (all static content updates)
> internation page minor content revisions

- app/views/dogs/show.html.erb
- app/views/layouts/maintentance.html.erb
- app/views/pages/guide.html.erb
- config/initializers/petfinder.rb
tiny refactor...   b/c life is better when you stay DRY
> DRY petfinder page links

- app/views/pages/guide.html.erb
> add link to dog gallery to adoption guide

- app/controllers/dogs_controller.rb
- app/models/adoptapet.rb
- app/models/dog.rb
- app/views/dogs/show.html.erb
- db/migrate/20180606150422_drop_adoptapet_ad_url_from_dogs.rb
- db/schema.rb
- spec/controllers/dogs_controller_spec.rb
- spec/factories/user.rb
- spec/features/dog_show_spec.rb
- spec/helpers/dog_show_helper.rb
- spec/models/adoptapet_spec.rb
- spec/models/dog_spec.rb
refactoring extracted from Bootstrap 4.1 upgrade work, so code review can be performed in smaller pieces.
> Adoptapet view model

- app/views/pages/international-article.html.erb
- app/views/pages/international-kaw.html.erb
- app/views/pages/international.html.erb
> internation page revisions

- app/views/pages/international.html.erb
> add links to international page

- app/models/photo.rb
I was not able to write a repro test for this. So it was tested manually. fixes #812.
> correctly invoke asset pipeline in models/photo.rb

- app/controllers/dogs_manager_controller.rb
- app/views/dogs_manager/_dog_form.html.erb
- app/views/dogs_manager/edit.html.erb
- app/views/dogs_manager/new.html.erb
- config/locales/en.yml
- spec/controllers/dogs_manager_controller_spec.rb
- spec/factories/dog.rb
- spec/features/dog_filter_spec.rb
- spec/features/dog_sort_spec.rb
- spec/features/dogs_manager_index_spec.rb
- spec/spec_helper.rb
Bootstrap 4.1 styling not yet addressed in the dog form. But I found that it didn't even work.
Added the creation of the tracking_id_seq sequence column in a 'before' callback of the test suite. Hopefully this will work on travis.
> fixes broken 'add dog' workflow

- config/locales/en.yml
> fix typo with donate translation

- app/views/pages/international.html.erb
> add byline to article

- app/views/pages/other_ways_to_give.html.erb
> add barkbox and target blank for external links

- app/helpers/about_dog_helper.rb
* Male dogs will now correctly display as neutered
* Fixes dog show second sentence.  It was displaying as "false" on the view if there were no caveats
> Minor hotfixes for the Dog Profile

- app/controllers/comments_controller.rb
- app/views/dogs/manager/_comments_audits.html.erb
> fixes #834 can now add new comments to dogs

- app/views/dogs/gallery/show.html.erb
- app/views/dogs/manager/show.html.erb
Fixes 500 Error when trying to view a dog without a size
> Fix for 500 error if dog has nil size

- app/views/pages/dog_status_definitions.html.erb
> Puts dog_status_definitions.html.erb back

- app/views/dogs/manager/show.html.erb
https://www.dropbox.com/s/o0sgbm8r69sd5p1/Screenshot%202018-07-16%2021.34.41.png?dl=0
fixes #837
> Puts attachments back on dog show page

- Gemfile
- Gemfile.lock
- app/controllers/dogs/manager_controller.rb
- app/models/dog_filter.rb
- app/views/dogs/manager/_manager.html.erb
- config/initializers/rack_profiler.rb
As per comments in #838 this sets pagination to run as part of the active record query.
> Fix for dog index performance

- Capfile
- config/deploy.rb
Notify newrelic monitoring system when a deployment runs.
> newrelic deploy notification support

- app/views/adopters/show.html.erb
- app/views/users/show.html.erb
fixes #858 Links to dogs from adoption apps or User accts should go to dog_manager/:id
> link to dog manager instead of gallery in user and adopter show pages

- app/controllers/users_controller.rb
- app/models/concerns/filterable.rb
- app/models/user.rb
- app/models/user_searcher.rb
- app/views/users/index.html.erb
- spec/controllers/users_controller_spec.rb
- spec/factories/user.rb
fixes for #859 NoMethodError when filtering Users from the User Index
> fixes #859 NoMethodError when filtering Users from the User Index

- .travis.yml
- README.md
- spec/features/dog_filter_spec.rb
- spec/features/dog_search_spec.rb
- spec/rails_helper.rb
TravisCI should run first with Chrome then with Firefox
> add firefox testing capability

- app/controllers/dogs/manager_controller.rb
- spec/controllers/dogs_manager_controller_spec.rb
closes #857 redirect unauthenticated users to dog public profile
> closes #857 redirect unauthenticated users to dog public profile

- config/environments/development.rb
- config/environments/test.rb
catch these errors before deployment!
> raise errors on translation missing in dev & test env

- .travis.yml
- spec/rails_helper.rb
Per: https://docs.travis-ci.com/user/speeding-up-the-build/#parallelizing-your-builds-across-virtual-machines
This is a try at getting the chrome_headless & firefox_headless tests to run in parallel.
> Run chrome and firefox tests in parallel on TravisCI

- app/models/dog.rb
- spec/features/dog_filter_spec.rb
- spec/models/dog_filter_spec.rb
- spec/models/dog_spec.rb
> closes #879 clear needs_foster status for adopted dogs

- app/views/pages/international-article.html.erb
- app/views/pages/international.html.erb
article edits per jess g.  Static content updates
> Desi article edits

- .rubocop.yml
- Gemfile
- Gemfile.lock
- spec/factories/adopter.rb
- spec/factories/adoption.rb
- spec/factories/adoption_app.rb
- spec/factories/banned_adopter.rb
- spec/factories/dog.rb
- spec/factories/event.rb
- spec/factories/folder.rb
- spec/factories/reference.rb
- spec/factories/shelter.rb
- spec/factories/user.rb
ref: [thoughtbot article](https://robots.thoughtbot.com/deprecating-static-attributes-in-factory_bot-4-11)
> fixes factorybot deprecations flagged by rubocop

- app/views/layouts/application.html.erb
Only run Google Analytics in Production
> Fix google analytics

- app/controllers/dogs/manager_controller.rb
- app/models/dog_filter.rb
- spec/controllers/dogs_manager_controller_spec.rb
excel spreadsheet results are affected by all current search and filter parameters, but without a pagination limit
> inhibit pagination for dogs excel download

- spec/helpers/dogs_list_helper.rb
This should fix some of the test failures that are in the PR queue now.  Re-running them should get them passing too (until this PR is merged) as the probability of dog name collision is low, but not zero.
> fixes occasional test failures due to dog name duplication

- spec/features/staff_resources_spec.rb
this should get the test suite back to green
> fix login call on folder tests

- app/views/attachments/_attachment.html.erb
- app/views/folders/_folder.html.erb
- app/views/folders/_folder_table.html.erb
- app/views/folders/_form.html.erb
- db/migrate/20180912034937_drop_folders_description_field.rb
- db/schema.rb
- spec/factories/folder.rb
- spec/features/staff_resources_spec.rb
second merge from non forked branch to ensure test suite goes green.
> Feature/folder description (2nd merge)

- app/controllers/donations_controller.rb
- app/views/donations/_donation.html.erb
- app/views/donations/history.html.erb
- app/views/donations/new.html.erb
- app/views/layouts/_topbar.html.erb
- app/views/layouts/_topbar_bs41.html.erb
- app/views/pages/donate.html.erb
- app/views/pages/get_involved.html.erb
- app/views/pages/international-article.html.erb
- app/views/pages/international-kaw.html.erb
- app/views/pages/international.html.erb
- db/migrate/20180922123913_add_comment_to_donations.rb
- db/schema.rb
Launch new donation system and add a comment field.
> Donation comment and launch

- db/seeds.rb
- lib/password_strategies/woof_bark.rb
- spec/features/clearance/migrate_from_woofbark_to_bcrypt_password.rb
On successful login will resave password as the bcrypt encrypted version.
> Adds encrypting password to bcrypt on successful login

- app/controllers/campaigns_controller.rb
- app/models/campaign.rb
- app/models/event.rb
- app/views/campaigns/_campaign.html.erb
- app/views/campaigns/_form.html.erb
- app/views/campaigns/index.html.erb
- app/views/campaigns/show.html.erb
- spec/controllers/campaigns_controller_spec.rb
- spec/factories/user.rb
- spec/features/campaign.spec.rb
- spec/support/shared_context.rb
Fixes client validation for Donation Campaigns
Add more tests
Use the Event Manager permission for adding and editing campaigns
> Use Event Permission for Campaign Management and Fixes

- app/views/pages/international-article.html.erb
- app/views/pages/international-kaw.html.erb
- app/views/pages/international.html.erb
> change links in international programs section to point to new donation campaign

- app/views/pages/international-article.html.erb
- app/views/pages/international-kaw.html.erb
- app/views/pages/international.html.erb
> adjust donation campaign wording

- app/views/pages/7000-miles-home.html.erb
- config/locales/en.yml
> minor article fixes

- app/assets/javascripts/adoption_form.js
- app/assets/stylesheets/custom.scss
- app/views/adopters/_adopter_other_pets_form.html.erb
- app/views/adopters/show.html.erb
- spec/features/edit_vet_spec.rb
closes #824
Vet information in the adoption application is now editable.  This is based on the same code we used for editing references and adopter info.
> vet info editable 

- app/views/donations/new.html.erb
> spelling correction on donate page

- app/assets/stylesheets/custom.scss
- app/controllers/pages_controller.rb
- app/views/layouts/_topbar_future.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/home_new.html.erb
Additional work in progress for the new home page.
> Future Home Page Update

- app/views/layouts/application.html.erb
minor hotfix to correct formatting of the bootstrap 2.3.2 pages.
> formatting fix for bootstrap 2.3.2 pages

- app/assets/stylesheets/custom.scss
- app/views/pages/guide.html.erb
- app/views/pages/home_new.html.erb
- config/locales/en.yml
> Bs4 home beta

- app/models/adopter.rb
> adopted, completed and adpt sn pend are all considered adopted for mailchimp

- spec/features/donation_spec.rb
ref https://github.com/rspec/rspec-core/issues/2179
> Trying to fix flaky tests.

- app/helpers/about_dog_helper.rb
> more positive dog bios wording

- app/controllers/campaigns_controller.rb
- app/helpers/campaigns_helper.rb
- app/models/campaign.rb
- app/views/campaigns/_form.html.erb
- app/views/campaigns/index.html.erb
- app/views/campaigns/show.html.erb
- app/views/layouts/_topbar.html.erb
- app/views/layouts/_topbar_bs41.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20190203202130_add_active_to_campaigns.rb
- db/schema.rb
- spec/controllers/campaigns_controller_spec.rb
Allows Fundraising Campaigns to be toggled as Active or Inactive.
> Toggle campaigns active or inactive

- lib/tasks/petfinder_sync.rake
This resolves issues where S3 HTTPS downloads will occasionally timeout
> petfinder sync - retry s3 image downloads in event of a timeout

- app/assets/stylesheets/custom.scss
- app/views/layouts/_topbar_bs41.html.erb
- app/views/pages/home.html.erb
Add oph logo to home page
Update Education numbers for home page
New color scheme for top menu bar
> Front page updates

- app/controllers/adopters_controller.rb
- app/controllers/application_controller.rb
- app/controllers/attachments_controller.rb
- app/controllers/banned_adopters_controller.rb
- app/controllers/campaigns_controller.rb
- app/controllers/comments_controller.rb
- app/controllers/dogs/manager_controller.rb
- app/controllers/donations_controller.rb
- app/controllers/events_controller.rb
- app/controllers/folder_attachments_controller.rb
- app/controllers/folders_controller.rb
- app/controllers/photos_controller.rb
- app/controllers/shelters_controller.rb
- app/controllers/users_controller.rb
- app/helpers/application_helper.rb
- app/helpers/sessions_helper.rb
- config/initializers/clearance.rb
- lib/clearance/locked_account_guard.rb
- spec/factories/adopter.rb
- spec/factories/breed.rb
- spec/factories/dog.rb
Fixed account locking and improves error messages.  Also will now immediately lock out a user with an active session.
> Update account locking

- app/assets/stylesheets/custom.scss
- app/controllers/dashboards_controller.rb
- app/views/dashboards/_adopter.html.erb
- app/views/dashboards/_dog.html.erb
- app/views/dashboards/_event.html.erb
- app/views/dashboards/index.html.erb
- config/routes.rb
- spec/features/dashboard_spec.rb
This is an initial prototype for a Volunteer dashboard. 
First set of features:
1. Upcoming events in a 10 mile radius of the volunteer
2. Quick link to any dogs the volunteer is currently fostering
3. Quick link to any adoption applications the volunteer is assigned
> Volunteer dashboard - first prototype

- app/controllers/dashboards_controller.rb
- app/views/dashboards/_adopter.html.erb
- app/views/dashboards/_bulletins.html.erb
- app/views/dashboards/_contacts.html.erb
- app/views/dashboards/_dog.html.erb
- app/views/dashboards/_event.html.erb
- app/views/dashboards/_opportunities.html.erb
- app/views/dashboards/index.html.erb
- spec/features/dashboard_spec.rb
Add some fake stuff to the volunteer dashboard and play around with styling.
> Dashboard mockup pass

- app/models/adopter_searcher.rb
- app/views/adopters/index.html.erb
- spec/models/adopter_searcher_spec.rb
Adopters can now be looked by by their phone number.  Valid search formats:
```
555-123-4567
(555) 123-4567
5551234567
```
> search for adopters by phone number

- app/controllers/dogs/manager_controller.rb
- app/models/dog.rb
- app/views/dogs/manager/_dog_form.html.erb
- app/views/dogs/manager/show.html.erb
- db/migrate/20190420182534_add_dewormer_and_toltrazuril_to_dogs.rb
- db/schema.rb
- spec/factories/dog.rb
- spec/features/dog/add_dog_spec.rb
- spec/features/dog/dog_manager_show_spec.rb
- spec/features/dog/edit_dog_spec.rb
- spec/features/dog/manage_dogs_spec.rb
- spec/models/dog_spec.rb
> Add dog vaccines

- app/assets/stylesheets/application_bs41.scss
- app/assets/stylesheets/custom.scss
- app/controllers/dashboards_controller.rb
- app/views/dashboards/_bulletins.html.erb
- app/views/dashboards/index.html.erb
- app/views/layouts/_topbar_user_bs41.html.erb
- app/views/layouts/application.html.erb
- spec/features/dashboard_spec.rb
Enhancements to the prototype volunteer dashboard.  Includes draft of a new top navbar for accessing common volunteer actions.
> streamline volunteer dashboard add user topbar

- app/views/pages/guide.html.erb
> remove non-microchipped dogs price from guide

- app/views/adopters/steps/_contact.html.erb
> help field for adopters out of adption area

- app/controllers/posts_controller.rb
- app/views/dashboards/_bulletin.html.erb
- app/views/dashboards/_opportunity.html.erb
- app/views/dashboards/index.html.erb
- spec/requests/bulletins_request_spec.rb
Posts can now be deleted
Improved formatting and spacing for the Dashboard
> Dashboard updates

- app/controllers/dashboards_controller.rb
- app/controllers/pages_controller.rb
- app/views/layouts/_topbar_user_bs41.html.erb
- app/views/pages/newsletter.html.erb
- config/locales/en.yml
- config/routes.rb
Provide a page where sent Mailchimp volunteer newsletters can be made available for view
> add volunteer newsletters page

- app/assets/stylesheets/shared_styles.scss
- app/controllers/events_controller.rb
- app/views/events/_event.html.erb
- app/views/events/_form.html.erb
- app/views/events/edit.html.erb
- app/views/events/index.html.erb
- app/views/events/new.html.erb
- app/views/events/show.html.erb
- spec/controllers/events_controller_spec.rb
- spec/features/event_management_spec.rb
> event layout improvements

- app/views/events/_event.html.erb
Add description back to event index as per org feedback.
> Event index

- app/assets/javascripts/event_structured_data.js
- app/views/events/show.html.erb
- config/initializers/assets.rb
issue #996 
I checked the event's show page structured data with google structured data tool.
> event structured data google

- app/models/event.rb
- spec/controllers/events_controller_spec.rb
> days with many events did not paginate correctly

- app/controllers/posts_controller.rb
- app/models/info.rb
- app/views/posts/_form.html.erb
- config/routes.rb
Should allow for an editable contacts page & other similar types of pages.
> add info type of editable content page

- app/views/pages/donate.html.erb
- lib/tasks/adoptapet_sync.rake
- lib/tasks/petfinder_sync.rake
Removes CFC notice and fixed a bug with the dog adoption urls
> Cfc and sync fix

- app/controllers/adopters_controller.rb
- app/mailers/bite_prevention_mailer.rb
- app/views/bite_prevention_mailer/bite_prevent.html.erb
- config/environments/test.rb
- spec/features/apply_to_adopt_spec.rb
Send email with info on preventing dog bites 24 hours after someone submits an adoption application.
> closes #1404 bite prevention email

- app/assets/javascripts/adoption_app_toggle_fields_display.js
- app/assets/javascripts/adoption_app_wizard.js
- app/assets/javascripts/application_common.js
- app/assets/javascripts/datepicker.js
- app/controllers/adopters_controller.rb
- app/models/adoption_app.rb
- app/views/adopt_app_mailer/adopt_app.html.erb
- app/views/adopters/_adopter_form.html.erb
- app/views/adopters/steps/_your_home.html.erb
- db/migrate/20190428181545_add_birth_date_to_adoption_apps.rb
- db/schema.rb
- spec/factories/adoption_app.rb
- spec/features/apply_to_adopt_spec.rb
- spec/mailers/previews/adopt_app_mailer_preview.rb
- spec/models/adoption_app_spec.rb
- spec/support/time_helpers.rb
* Add birth date and adopter age to adoption app
* Add birth date and adopter age to adopt app mailer and add mailer preview
* Fix adopter age in adoption app and add tests
* Fix comment in mailer preview and make adoption age plural in all cases except for 1
(pulled into repo so that TravisCI can run)
> Add birth date to adoption app (#1185)

- app/models/user.rb
- app/views/users/_user.html.erb
- app/views/users/_user_table.html.erb
> Foster search returns current foster animals closes #922

- app/views/pages/training_partners.html.erb
> trainer updates

- app/models/user_searcher.rb
- app/views/users/_foster_filters.html.erb
- app/views/users/_user.html.erb
- app/views/users/_user_table.html.erb
- app/views/users/index.html.erb
After filtering users by location, it is now possible to additionally filter by a specific role.  
UI will be cleaned up and redone as part of migration to Bootstrap 4 at a later time.
> user roles now filterable by location

- app/views/pages/home.html.erb
- spec/features/cat/cats_gallery_spec.rb
- spec/features/dog/dogs_gallery_spec.rb
> fix gallery tests

- Gemfile
- Gemfile.lock
- app/controllers/treatment_records_controller.rb
- app/views/layouts/pdf.html.erb
- app/views/treatment_records/_available_treatment.html.erb
- app/views/treatment_records/_treatment_record.html.erb
- app/views/treatment_records/_treatment_record.pdf.erb
- app/views/treatment_records/edit.html.erb
- app/views/treatment_records/index.html.erb
- app/views/treatment_records/index.pdf.erb
- app/views/treatment_records/new.html.erb
- app/views/treatments/_treatment.html.erb
- app/views/treatments/index.html.erb
- app/views/treatments/show.html.erb
- config/initializers/mime_types.rb
- config/initializers/wicked_pdf.rb
UI improvements for Treatment Records, and the ability to render a very ugly PDF
> Treatment Record UI fixes and basic Pdf export plumbing

- app/assets/javascripts/animals_index.js
- app/models/dog.rb
- app/views/dogs/manager/_manager.html.erb
- spec/features/dog/dog_filter_spec.rb
- spec/features/dog/dog_search_spec.rb
- spec/helpers/dogs_list_helper.rb
#849 
Adds search bar on top of filter/sort card on Dog Manager index
> Make dog search options bar more prominent

- app/controllers/adopters_controller.rb
- app/models/adopter.rb
- app/views/adopters/_adopter.html.erb
- app/views/adopters/_dog_choices.html.erb
- app/views/adopters/index.html.erb
- app/views/adopters/steps/_dog.html.erb
- db/migrate/20200612044120_add_dog_or_cat_to_adopters.rb
- db/schema.rb
- spec/features/apply_to_adopt_spec.rb
- spec/models/adopter_spec.rb
Adds required question for dog or cat request on the adoption application form. 
Results visible on adopter show - under Pet Choices - and index 
Apply to Adopt spec test amended
Closes #1556
> adds dog or cat question to adopt app

- app/assets/javascripts/adoption_form.js
- app/views/adopters/_dog_choices.html.erb
- app/views/adopters/steps/_dog.html.erb
Creates a drop down menu if dog_or_cat not previously set to select Dog or Cat
Edited adoption_form.js to add autosave similar to Pet Selections
Fixed indentation on dog.html.erb
fixes #1564
> adopters set dog_or_cat on old apps

- config/initializers/session_store.rb
https://github.com/rails/rails/issues/21948
> extend session cookie to work around CSRF issues

- app/views/adopters/steps/_other_pets.html.erb
Makes :current_info required in response to :prev_pets_type and :current_pets_type additions
> make current_pets required

- app/views/donations/new.html.erb
- spec/features/campaign.spec.rb
- spec/features/donation_spec.rb
changes the 25 dollar donation button to a 20 dollar donation button in support of raffle
> $20  donation button as reqstd for raffle campaign

- app/views/users/index.html.erb
Adds Bootstrap 4 styling for User Index pagination
closes #1606
> fix user pagination style

- app/assets/stylesheets/dogs_index/_manager_dog.scss
- app/views/cats/manager/_cat.html.erb
- app/views/dogs/manager/_dog.html.erb
Changes proposed in this pull request:
* Added primary photo on cat mgr and dog mgr
* Added primary photo's class to _manager_dog_.scss manage position and size
* Modified some _manager_dog_.scss tags for better behavior
> Feature 1605: add image thumbnail to dog/cat mgr

- app/models/adoption.rb
- app/models/cat_adoption.rb
For situations where someone may have paid
for a dog and later changed their mind
> allow for "canceled" as an adoption relationship

- app/views/treatment_records/_cat_vaccinations.pdf.erb
- app/views/treatment_records/_dog_vaccinations.pdf.erb
- app/views/treatment_records/index.pdf.erb
> cat vaccination recommendations

- app/mailers/adopt_app_mailer.rb
- app/models/adopter.rb
- app/views/adopt_app_mailer/approved_to_adopt.html.erb
- spec/mailers/previews/adopt_app_mailer_preview.rb
As requested by Laurie, email notification with video link send to adopters when their application is approved.
> adds approved to adopt notice

- app/views/pages/international.html.erb
Static Content update for international page
> adds hope for hope box

- app/assets/stylesheets/staff_resources.scss
- app/controllers/folder_attachments_controller.rb
- app/controllers/folders_controller.rb
- app/views/adopters/_adopter_housing.html.erb
- app/views/attachments/_attachment.html.erb
- app/views/folder_attachments/_attachment_table.html.erb
- app/views/folder_attachments/index.html.erb
- app/views/folders/_folder_table.html.erb
- app/views/folders/_form.html.erb
- app/views/folders/edit.html.erb
- app/views/folders/index.html.erb
- app/views/folders/new.html.erb
- app/views/folders/show.html.erb
- spec/features/staff_resources_spec.rb
- Updates folders to Bootstrap 4
- Deletes file name column 
- Adds file url to file description
closes #1591
> Feature/update bootstrap folders #1591

- app/controllers/adopters_controller.rb
- app/models/adopter_searcher.rb
- spec/models/adopter_searcher_spec.rb
* Eliminates circular references
* Moves the "show" filter to (adopters_controler.rb)[app/controllers/adopters_controller.rb]
> Fixes 1637: circular argument references

- app/views/cats/manager/_cat_attachments.html.erb
- app/views/cats/manager/_cat_form.html.erb
- app/views/cats/manager/_cat_photos.html.erb
- app/views/dogs/manager/_dog_photos.html.erb
- db/schema.rb
Adds responsive timestamps to cat_manager and dog_manager edit forms
Closes #1640
> add pet manager photo  timestamps #1640

- app/controllers/adopters_controller.rb
- app/models/adopter_searcher.rb
- spec/models/adopter_searcher_spec.rb
And add test case for next try
Resolves defect #1662 by rolling back code, and adds a new test case.
> Rollback of #1649 fix for AdopterSearcher

- app/assets/javascripts/adoption_form.js
- app/assets/stylesheets/custom.scss
- app/views/adopters/_dog_choices.html.erb
- app/views/adopters/show.html.erb
- spec/factories/adopter.rb
- spec/features/edit_pet_choices_spec.rb
- adds editable fields to each row in Pet Choices
- adds testing to ensure it works 
- adds Dog or Cat to Adopter Factory to prevent testing for nil value 
closes #1696
> #1696 make pet choices editable

- app/models/adopter.rb
Mailchimp no longer likes receiving an empty MMERGE3 value, removing
> hotfix for mailchimp update errors could refactor

- app/controllers/users_controller.rb
- app/models/attachment.rb
- app/models/user.rb
- app/views/users/_form.html.erb
- app/views/users/show.html.erb
- db/migrate/20201014212102_add_insurance_training_id_to_users.rb
- db/schema.rb
- spec/features/attach_agreement_to_user_spec.rb
Adds  a new attachment field to volunteer profile that can be updated directly by the volunteer.
> adds insurance training attachment to user profile

- .github/workflows/main.yml
- app/controllers/adoption_app_controller.rb
Fix for failing CI builds, ref https://github.com/sass/sassc-ruby/issues/146#issuecomment-771042986
> additional save feedback for adoption apps and ci fix

- app/views/adopters/steps/_your_home.html.erb
- app/views/cats/manager/_cat_form.html.erb
- app/views/cats/manager/_private_information.html.erb
- app/views/cats/manager/show.html.erb
- app/views/dogs/manager/_dog_form.html.erb
- app/views/dogs/manager/_private_information.html.erb
- app/views/dogs/manager/show.html.erb
- app/views/pages/resources.html.erb
- spec/controllers/adopters_controller_spec.rb
- spec/features/cat/add_cat_spec.rb
- spec/features/cat/edit_cat_spec.rb
- spec/features/dog/add_dog_spec.rb
- spec/features/dog/edit_dog_spec.rb
removed as per request of Erin
> initial removal of craigslist fields

- app/controllers/volunteer_apps_controller.rb
- app/models/volunteer_app.rb
- app/models/volunteer_app_searcher.rb
- app/views/layouts/_topbar.html.erb
- app/views/layouts/_topbar_bs41.html.erb
- app/views/layouts/_topbar_user_bs41.html.erb
- app/views/volunteer_apps/_volunteer_app.html.erb
Name and Email must be unique
Sort by created_at DESC
Show when apps were submitted
Default view to new applications
Status is now 'Ready for Call ORT'
> Volunteer Application Enhancements

- app/controllers/badges_controller.rb
- app/controllers/users_badges_controller.rb
- app/models/user.rb
- app/views/badges/_badge.html.erb
- app/views/badges/index.html.erb
- app/views/badges/show.html.erb
- app/views/users/show.html.erb
- config/routes.rb
- spec/factories/user_badge.rb
- spec/requests/badges_request_spec.rb
- spec/requests/users_badges_request_spec.rb
This feature allows users to add and remove achievement badges from their profile by selecting from a list of available badges.
https://share.getcloudapp.com/o0ue6nmN
> user badge management

- app/models/adopter.rb
- app/views/adopters/_adopter_form.html.erb
Following Adoption Application Fields are now editable:
* Name
* Spouse Name
* Best time to call
* Where did you hear about us
> Remaining Adopter Application Fields are editable

- .github/workflows/main.yml
Clear some deprecation warnings
> Github Action Updates

- .github/workflows/main.yml
Reverts ophrescue/RescueRails#2366
> Revert "github actions updates"
