ophrescue/RescueRails

app/assets/javascripts/adoption_app_wizard.js
tested in Chrome, IE11 and IE9.  Works like a charm
=> resolves #358 by removing whitespace from applicant email

app/controllers/comments_controller.rb
User will now get prompted to reenter credentials.
However it renders in the past comments section instead of
refreshing the page.  Dont thinks its worth ripping the jquery apart to make this elegent.
=> resolves #384 error creating comments when not signed in

app/models/event.rb
caught this in the error logs.  Looks like after the sdk upgrade it's supposed to be ```public-read``` now instead of ```public_read```.  From the paperclip s3 docs, the default is public read anyway, so just deleted the line!
=> fixes #463 s3 api error on event photos

vendor/assets/stylesheets/link_icons.scss
During the rails 5 upgrade a test kept failing because icon_mail.gif was
missing.  I'm not sure why rails 4 let this go without reporting a missing image but rails 5 is VERY ANGRY.
Currently broken on production, check out the contact page, https://ophrescue.org/contact
The after
=> Fixes mailto link icon

app/assets/javascripts/comments.js, app/views/adopters/_adopter_comment_form.html.erb, app/views/dogs/show.html.erb
Was able to verify that for comments on dogs or adopters after a comment was posted, the Post button wouldn't re-enable and folks have to refresh the page for the post button to start working again.
This appears to fix the issue.  Though I'm not sure why it started in the first place, or if there is a cleaner way to handle it.   
Thanks!
=> fix for #524 renable commit button after post

app/controllers/dogs_controller.rb, spec/controllers/dogs_controller_spec.rb
This should fix #553 which was introduced in PR #552 
Gallery view is supposed to work the same regardless of if you're logged in or not.  We introduced an issue where if logged in all dogs ever would show up in the gallery view.  Totally missed that in my review.  
I've added a whole bunch of tests that should verify behavior.
=> bugfix if logged in only public view dogs should be in gallery view

app/assets/javascripts/adoption_form.js
No clue how this got removed, must have been when renaming files and such. How has no one noticed this?  You can't edit adopters currently.
=> Restores edit form capability

app/models/user.rb, db/migrate/20170923045153_change_user_address_column_names.rb, db/schema.rb
I wanted to see if this makes sense or not before going too far with it - I took a look at what refactoring would be required to fully flesh this out and it's extremely doable so far as I can tell.
**Motivation:**
The desire is to move from supporting exclusively US mailing addresses to supporting international addresses, starting with Canada. Countries are not consistent with how they name their administrative divisions. "Region" appears to be a conventional term for the principal subdivisions of a country - whether they're states, provinces, or other. As a single reference point, see http://schema.org/PostalAddress
Additionally, a ZIP code is a particular type of postal code, but the terminology "ZIP code" is specific to the US, so this changes to use a more generic term.
I find it's …
=> #437: Change 'state' to 'region' and 'zip' to 'postal code'

app/models/folder_searcher.rb, db/schema.rb, spec/models/folder_searcher_spec.rb
fixes #639
Updated `folder_searcher` to only return `Attachments` that have the `attachable_type` of `Folder`.
Does this solution cause too many queries to the DB?
=> fixes #639

app/controllers/users_controller.rb, app/helpers/users_helper.rb, app/models/user.rb, app/views/users/_form.html.erb, app/views/users/_user.html.erb, app/views/users/show.html.erb, db/seeds.rb, spec/controllers/users_controller_spec.rb, spec/factories/user.rb, spec/models/user_spec.rb
Application layer refactor that corresponds to [this database migration](https://github.com/ophrescue/RescueRails/pull/629). The UI is unchanged, so now the field labeled `state` corresponds to the attribute `region` and the field labeled `zip` corresponds to the attribute `postal_code`. This is to support upcoming work that will conditionally change the UI to show localized labels - "Province" and "Postal Code" for Canadian addresses.
=> #437: Change User 'state' to 'region' and 'zip' to 'postal code'

spec/features/apply_to_adopt_spec.rb, spec/rails_helper.rb
Use 'set' instead of 'native.send_keys'. It seems to work... I ran 2 builds on the CI successfully, and a handful locally without issue. Not sure if you've tried this before.
=> Remove sleep during specs

spec/rails_helper.rb, spec/spec_helper.rb
This has two separate changes. The simple change is moving the `SimpleCov` initialization code from `rails_helper` to `spec_helper` - `SimpleCov` needs to be `require`'d before any other application code, or it won't be able to track coverage on that code. Practically speaking, this doesn't look like it makes any difference whatsoever with the current implementation, but as `spec_helper` is `require`'d before `rails_helper`, the initialization code should be in `spec_helper`.
Secondly, it looks like we currently use the default configuration of SimpleCov. There's a different configuration for Rails projects that tries to make some sensible decisions about what to test and what not to test. See [documentation](https://github.com/colszowka/simplecov#profiles) for more info. 
I was hoping …
=> Use rails simplecov configuration

Gemfile, Gemfile.lock, app/models/user.rb, app/services/country_service.rb, config/initializers/countries.rb, spec/models/user_spec.rb, spec/services/country_service_spec.rb
Adds validation that the country is either `USA` or `CAN`. The behavior to default all users to `USA` if it's not otherwise specified is still in place. Functionally I don't expect this to change anything, it's just another step closer to supporting two different countries.
=> 437: Validate user country

app/models/user.rb, spec/models/user_spec.rb
Before this fix is merged, the production database should be checked for invalid data. For example, anything returned by:
`SELECT id, name, email, postal_code FROM users WHERE postal_code !~ '\A\Z|\A\d{5}(?:-\d{4})?\Z';`
will be invalid after this has been merged.
Fixes #654. The regular expression used was missing the terminating character in the first alternative expression. This means that any value could be used for the ZIP so long as it started with 5 digits followed by 4 digits.
=> #654: Fix user ZIP code validation regex

Gemfile, Gemfile.lock, app/models/user.rb, app/validators/region_validator.rb, spec/features/manage_dogs_spec.rb, spec/models/user_spec.rb, spec/validators/region_validator_spec.rb
Continuing the saga of support for Canadian addresses, this introduces validation on the region (state/province) when the country is Canada. The region code is validated to be 2 letters regardless, but when the user has a Canadian address the region is additionally checked to ensure it's actually a province.
=> Add region validator

app/models/user.rb, app/validators/postal_code_validator.rb, spec/validators/postal_code_validator_spec.rb
As the final piece of Canadian address validation, this introduces a postal code validator for both US ZIP codes and Canadian postal codes. Validation remains the same as before for US addresses (with the quirk that it can't be validated if the country isn't specified), and it validates only that it's the right form for Canadian postal codes. I didn't look at all at code to check it's a real postal code.
=> 437: Add validator for postal code

app/models/user.rb, app/validators/postal_code_validator.rb, spec/models/user_spec.rb
Fixes bug I accidentally introduced in [this PR](https://github.com/ophrescue/RescueRails/pull/657). The validation I introduced was operating on a manipulated version of the model's attribute. This sanitizes the postal code (removes whitespace and converts letters to upper case) before validation.
=> #437: Sanitize postal code before validation

app/models/user.rb, app/validators/postal_code_validator.rb, app/views/users/_form.html.erb, spec/models/user_spec.rb
Incorporates PR #661, so hoping that gets merged shortly. This adds the country to the `user` form. I went for the easiest UI I could think of for the first pass.
=> 437 add country to user form

app/models/user.rb, spec/models/user_spec.rb
The current authentication and session logic is not particularly well covered by specs. Wrote some specs to understand the current behavior to make it easier to switch to Devise without regressions.
Also noticed that `generate_token` is only used within `User`, so easier to make it private than write specs for it!
=> 580: Add user tests

spec/support/shared_context.rb
Tiny piece of the puzzle I found while looking at all the test failures I have locally when I tried cutting over to Devise.
There are two shared contexts defined, an admin context and a regular user context. Before this change, despite being named differently they were the same. It seems like the intention is that a "user" does not have admin privileges, so this strips the admin privileges.
=> Remove admin privileges from regular user context

app/assets/stylesheets/custom.scss
The cursor was switching to move when it wasn't over the actual 'move handle' for the dog photo sort.  This was causing a lot of confusion.
=> change mouse cursor to move only when it is over something movable

.travis.yml, Gemfile, Gemfile.lock, db/migrate/20171221012248_install_audited.rb, db/schema.rb
Humble Beginnings for #682 
This gets our audited gem installed and audit table created using the jsonb datatype introduced in Postgresql 9.4.
Initial testing of audited shows that implementation is pretty easy, most of the work will be on getting the views to look good.
=> install audited with jsonb support

app/assets/javascripts/adoption_app_wizard.js, app/models/adoption_app.rb
The spouse_name database column is only 50 chars.  Validations were set too long.
=> corrected spouse_name validation to be 50 chars

app/views/pages/donate.html.erb
Per feedback from Kristina.
* Shrunk the "How can I help?" images to be 100px each
* Added `thumbnail-no-border` class to remove boarder as requested
* Added Horizontal line 
* Added text about anonymous donations.
=> Minor revisions to donation page

app/views/pages/5k.html.erb, config/routes.rb
The 5k promotion team is starting a social media campaign for the upcoming OPH 5k.  They'd like to be able to track visitors to the `/5k` link via Google Analytics.  
This change creates an actual page which should provide some time for Google Analytics to fire off and collect the event and related details.    Suggestions on if there is a better way to pull this off are appreciated.
=> redirect tracking for  5k registration

lib/tasks/adoptapet_sync.rake
adjust the adopapet sync so that their Good with Dog, Cats or Kids options is either set to No or Blank to keep more in line with how those fields are used in our own system.
=> never affirm a dog is good with cats kids or dogs

app/views/users/_form.html.erb
connects to #769
Should help with Browsers trying to autocomplete the change password fields.
=> closes #769 fix autocomplete for password change

app/views/dogs/_manager.html.erb, app/views/dogs/index.html.erb, app/views/dogs/show.html.erb, app/views/layouts/_topbar.html.erb
Had multiple feedback requests to adjust Dog Manager default view to not have any statuses set by default.
=> Users prefer dog manager to have no statuses set by default

.gitignore, spec/features/apply_to_adopt_spec.rb
The errors are due to the fact that the spec attempts to get to the adoption application by way of the link that cycles through as part of the front page image carousel. So there's a chance that it will not appear in time to be clicked from the spec.
This PR instead navigates to the adoption application via the nav bar menu.
=> fixes occasional errors in apply_to_adopt_spec

lib/tasks/populate_db.rake
I don't know why the error didn't show up before. FactoryBot.find_definitions is called during initialization, it causes errors to call it again.
(No production code changed in this PR, it can be safely merged)
=> remove find_definitions as it causes rake failures

.gitignore, app/controllers/dogs_controller.rb
I just noticed that the flash refactor I did previously was allowing the "dog unavailable" message to persist onto the next request.
=> fixes issue where flash persists to the next request

lib/tasks/adoptapet_sync.rake, spec/factories/dog.rb, spec/factories/user.rb, spec/spec_helper.rb, spec/support/tasks.rb, spec/tasks/adoptapet_sync_spec.rb
I noticed what appeared to be a bug in the rake task for adoptapet sync. The intention _appears_ to be that the urls of the four most recent photos should be included in the uploaded csv.
However, by inspection of the code, this was not happening, and  a test (see spec/tasks/adoptapet_sync_spec.rb) confirmed that it was not.
=> most recent photos were not being selected for inclusion

app/controllers/users_controller.rb, app/views/users/index.html.erb, spec/controllers/users_controller_spec.rb
Simple excel dump of user data to help management do cleanup of user accounts.  
Ideally the xls format would be blocked unless someone had admin permissions, instead of just a button hide.   So far my attempts at getting that to work in a `:before_action` have been futile.  I think that restriction is more of a nice to have than a must have.  
Regardless, if anyone has some suggestions, lmk.  Thanks!
=> Excel download of User Data

spec/features/link_dogs_to_adopters_spec.rb
This test bombs out on travis sometimes and frequently on my local test env as well.  Allowed capybara a few extra seconds to watch for the value to come up helps immensely.
=> flakey test fix - link dogs to adopters spec

config/locales/en.yml
Quick fix for missing translations on the Dog Gallery Index and Dog Manager index
=> quick fix for missing translations

app/assets/javascripts/dogs_index.js, app/views/dogs/manager/_dog_form.html.erb
Our dear friend IE11 doesn't like ES6 syntax.    And we have some users that are stuck with ie11 due to the usual corporate stuff. 
This fixes the IE11 issues #856 #855 #854
=> Roll back ie ES5 syntax to Fix ie11 problems

app/assets/javascripts/html5_bootstrap_form_validation.js
IE11 was exhibiting "flakey" behaviour in the HTML5 form validation process.
The existence and the fix are verified manually, as it is not yet possible to run the test suite on IE. In fact the bug surfaced whilst debugging running the test suite on IE.
Because this is a defect, it should be committed and deployed ahead of the availability of the test suite running on IE.
=> fixes ie11 form validation errors

.travis.yml, README.md, lib/tasks/test_suite.rake, spec/drivers/selenium_chrome_headless.rb, spec/drivers/selenium_firefox.rb, spec/drivers/selenium_firefox_headless.rb, spec/rails_helper.rb
Add driver and environment variable switch to run Firefox in non-headless mode, to facilitate debugging of Firefox-specific test failures.
Invoke Firefox headless with:
```
BROWSER=firefox_headless rspec spec
```
Invoke Firefox non-headless with:
```
BROWSER=firefox rspec spec
```
Run entire suite with both Chrome headless and Firefox headless with (as we do on TravisCi):
```
rake rescue_rails:test_suite
```
=> Firefox non headless

app/models/event.rb, spec/models/event_spec.rb
was failing to validate when location_url was blank, apparently this was not the intended behaviour
=> fixes Event validation error

app/controllers/sessions_controller.rb
We've had sporadic errors in the logs from legit users getting Invalid Auth token errors since pretty much forever.  Difficult to replicate the error, but we'll see if this finally does the trick.
Ref:  https://blog.alex-miller.co/rails/2017/01/07/rails-authenticity-token-and-mobile-safari.html
=> fix invalid auth header for mobile safari

.travis.yml
This limits the firefix_headless build job to only run the feature tests.  Sadly didn't make too much of a different in test builds so far, but still a good idea!
Thanks @lazylester
=> Limit Travis Firefox build to only feature branches

app/helpers/dogs_helper.rb, spec/features/dog_filter_spec.rb
=> fixes #887 Reset Filter Sort no longer appearing on Dog Manager Index

app/views/audited/audits/_audit.html.erb, app/views/dogs/manager/show.html.erb
errors don't seem to affect the rendering, but IE11 (correctly) reports the errors not reported by other browsers
=> fix html errors reported by IE11

spec/spec_helper.rb
fixes a problem when running tests on local machine (not travis), cleanup of precompiled assets removed the assets but not the manifest file.
=> remove .sprockets_manifest after tests finished

app/views/dogs/gallery/show.html.erb, app/views/dogs/manager/show.html.erb
upgrade to galleria v 1.5.7 was necessary to eliminate errors that were apparently related to the bootstrap upgrade
however galleria v 1.5.7 "swipe" feature causes failure of the context menu triggered by mobile device "long press".
In this PR. the galleria "swipe" feature has been disabled via its options config. So we are choosing to have the context menu and forego the swipe feature.
Someone who has much better js chops than me could probably figure out the reason why galleria's swipe feature borks the context menu. 
I have submitted an issue to [galleria github repo](https://github.com/worseisbetter/galleria/issues/403#issue-353964208) But there does not seem to be much activity resolving issues over there.
=> fixes #900, context menu not available on mobile devices

Gemfile, Gemfile.lock
It looks like this is used in commented out code in the banned adopters controller.
@markottaviani do we still do banned adopter importing from spreadsheets?
=> Removes unused roo gem which has security issue

app/controllers/dogs/manager_controller.rb, app/views/dogs/manager/_dog_form.html.erb, spec/features/add_dog_spec.rb, spec/features/dogs_manager_index_spec.rb, spec/features/edit_dog_spec.rb
when editing a dog and cancelling, it was returning to the index page, but should more appropriately return to the dog manager profile page, where the user was prior to editing
=> on edit cancel, return to dog profile

Gemfile, Gemfile.lock, app/models/photo.rb
Included only in the photo model, but apparently no longer used as the position attribute is managed by our own code.
=> remove acts_as_list unused gem

app/views/sessions/new.html.erb, config/initializers/clearance.rb
The session expires when the browser is closed with no way to "remember me". I'm pretty sure this was in the code at some point but probably got lost in the rebasing mess.
This also makes the sessions last 1 week vs. 1 year.
=> Adds remember me checkbox to sign in

app/models/google_map.rb, app/views/events/_event.html.erb, spec/features/event_management_spec.rb
Fixes for mobile view of events index.  
Switch Google Maps to be just a link instead of rendering a static map due to removal of google maps static map free tier.
=> Event page Fix mobile view and Google Maps Links

app/models/dog.rb, spec/controllers/dogs_gallery_controller_spec.rb
Adoptable dogs will be displayed first, followed by coming soon dogs and then adoption pending. Within each of these three groups, dogs will continue to be sorted in ascending order by their tracking id numbers.
=> Dog gallery sort update

spec/tasks/adoptapet_sync_spec.rb
Any idea what I'm missing here?
I made a change in 160eed302cf0cdecfc6ee5abcd147c985cc5f28a to the adoptapet sync.   Change makes the adoptapet sync send the 4 top ranked photos by position order instead of 4 most recent uploaded photos.  
I didn't update the test 👎 
Trying to make right on that, but can't seem to get this thing green.  Any idea what I'm missing?
```
Failure/Error: expect(csv_photos).to eq photo_urls
expected: ["/system/test/photos/0c3e99740ee5a5cb5b6b3ea702e40cf86fcda327.jpeg", "/system/test/photos/4fb926fd55...4b0cebf79b9792ff3a21e389.jpeg", "/system/test/photos/9727826a3cc0fe0d4cc94b974c69a4786035bdf3.jpeg"]
got: ["/system/test/photos/0c3e99740ee5a5cb5b6b3ea702e40cf86fcda327.jpeg", "/system/test/photos/4fb926fd55...15be2af5a98040e0ce7f8af3.jpeg", …
```
=> fixing adopapet sync test

Gemfile, Gemfile.lock, spec/drivers/selenium_chrome_headless.rb, spec/rails_helper.rb
tmp lock chromedriver to 2.40 to keep tests green
=> migrate to webdrivers gem

app/assets/javascripts/comments.js
clicking the edit button on a comment when using an iPad or iPhone didn't work.  Needed to also watch for the `touchstart` event to get the toggle working
=> comments are now editable on touch devices

app/models/user.rb
Adjusted the paperclip filename to save as  `:hash.:extension` instead of just `.extension` which resulted in pretty minimal options for filenames :)
https://cl.ly/0dbdbb1ebdf6
=> filename fix for user profile images

app/models/user.rb, app/views/users/show.html.erb
Tracks all changes to a User's permissions, and makes history visible on user's show page.
=> closes #1403 add user permission auditing

Gemfile.lock, spec/support/geocoder_stubs.rb
adds fix for the geocoder test stub.
=> Bump geocoder from 1.4.9 to 1.6.1 with test fixes

Gemfile.lock, spec/features/cat/cat_search_spec.rb, spec/features/dog/dog_search_spec.rb, spec/features/staff_resources_spec.rb, spec/helpers/application_helpers.rb
Looks like they changed the class that gets applied to the default notice.  All tests should pass now with the upgrade to clearance 2.1
=> Updates clearance and fixes tests

spec/features/cat/edit_cat_spec.rb, spec/features/dog/edit_dog_spec.rb
Fix for the tracking_id collisions
=> remove hard coded tracking ids for better test reliability

app/assets/javascripts/adoption_form.js, app/assets/stylesheets/custom.scss, app/controllers/adopters_controller.rb, app/views/adopters/_adopter_form.html.erb, app/views/adopters/_adopter_rental.html.erb, app/views/adopters/steps/_rental.html.erb, spec/features/edit_rental_spec.rb
Makes other_household_names and other_phone editable
Makes rental info editable
Fixes typo on _rental.html.erb
Currently appears on history tab, but editing the info in _adopter_form.html.erb returns a unrecognized parameters :id error. 
will close #1569 and #1072
=> adopter add editable fields in form and rental

.travis.yml
Removing rspec run using Firefox/geckodriver as it takes twice as long to run  as our chrome based tests and throws false failures often.  
Since we're using an established front end framework, risk of major issues from Chrome to Firefox are fairly low.
=> Remove Firefox test job on TravisCI

app/controllers/adopters_controller.rb, app/models/adopter_searcher.rb, app/models/adoption.rb, app/views/adopters/index.html.erb, app/views/layouts/_topbar.html.erb, app/views/layouts/_topbar_bs41.html.erb, app/views/layouts/_topbar_user_bs41.html.erb, spec/models/adopter_searcher_spec.rb
**Fulfills OPH_request, issue #1584**
Edits adopter_searcher.search
- Adopter list displayed according to the selected filtering button
- "All applications" does not add a filter to the list
Edits filtering buttons behavior:
- "My Applications" show applications assigned to the logged User
- "Open Applications" show applications that are unassigned
- "All Applications" show all applications
Adds 'display filtered adopters' in adopter_searcher_spec
_By default "My applications" are displayed (may break client expectations of seeing all applications when entering)_
=> #1584 Filter applications

app/views/adopters/_adopter_form.html.erb, app/views/adopters/_adopter_other_pets_form.html.erb, app/views/adopters/steps/_other_pets.html.erb
- Makes Vet Info required and always visible 
- Adds 'None' option to prev_pets_type on application and editable
- Fixes First Time Dog / Cat label logic (adds in current_pet_types as a factor) 
closes #1607
=> fix vet_info #1607

app/models/cat.rb, app/models/dog.rb, app/views/cats/manager/_cat_form.html.erb, app/views/dogs/manager/_dog_form.html.erb, spec/factories/cat.rb, spec/factories/dog.rb, spec/features/cat/add_cat_spec.rb, spec/features/cat/edit_cat_spec.rb, spec/features/dog/add_dog_spec.rb, spec/features/dog/edit_dog_spec.rb, spec/models/cat_spec.rb, spec/models/dog_spec.rb
* Add microchip_validation method in [dog](app/models/dog.rb) and [cat](app/models/cat.rb) models
* Add validation_class to microchip field in [dog](app/views/dogs/manager/_dog_form.html.erb) and [cat](app/views/cats/manager/_cat_form.html.erb) views
* Changed [dog](spec/factories/dog.rb) and [cat](spec/factories/cat.rb) factories to comply with microchip format
*  Changed input value of specs ([dog](spec/models/dog_spec.rb), [cat](spec/models/cat_spec.rb), [add_cat](spec/features/cat/add_cat_spec.rb), [edit_cat](spec/features/cat/edit_cat_spec.rb), [add_dog](spec/features/dog/add_dog_spec.rb) & [edit_dog](spec/features/dog/edit_dog_spec.rb)) to comply with microchip format
=> Feature 762: Microchip validation

app/controllers/adopters_controller.rb, app/models/adopter_searcher.rb, spec/models/adopter_searcher_spec.rb
- Eliminates circular references
- Moves the "show" filter to [adopters_controler.rb](app/controllers/adopters_controller.rb)
=> Fix circular argument references in adopter_searcher

app/models/adopter.rb, spec/controllers/adopters_controller_spec.rb
app/models/adopter.rb
- Training email now triggers off of changing relation_type to "adopted" && Dog adoptions only 
- Chimp check triggers off status change or relation_type change
- Followup email triggers off of changing relation_type to "adopted" && Dog adoptions only
spec/controllers/adopters_controller_spec.rb
- tests changed to prove emails trigger from relation_type change not status change
- added test to prove cat adoptions do not trigger training / followup emails
- added test to prove 2 emails sent per adoption 
closes #1659
=> Feature/training to each dog adopt #1659

app/helpers/about_animal_helper.rb
Remove shot and spay/neuter info from public profile as it can be confusing.  Per OPH request.
=> Don't show medical info on pet bios
